version: 0.2

phases: 
  install:
    runtime-version:
      docker: 18
      nodejs: 16
    prebuild:
      commands:
        - echo Installing Dependencies
        - npm install
        - ${aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION}
    build:
      commands:
        - echo Build
        - npm run build
        - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG
        - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    post_build:
      commands:
        - echo Pushing the docker image
        - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imageDetail.json

artifacts:
  files: imageDetail.json